# site settings
title: Paulina Colmenares
subtitle: Choreography
email: acolmena@ucsd.edu
description: I'm a Mexico-based choreographer<br /> with an MFA from UC San Diego.
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: Santa Catarina Martir s/n
city: Cholula 
state: Pue
zip_code: 55555
country: México
phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: https://www.facebook.com/paulinacolmenares
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com/paulinacolmenaresdanza
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
